CREATE TABLE `Files` (
	`FileId` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`CreationTimeUtc` DATETIME NOT NULL,
	`LastAccessTimeUtc` DATETIME NOT NULL,
	`LastWriteTimeUtc` DATETIME NOT NULL,
	`FileSize` BIGINT(20) NOT NULL DEFAULT '0',
	`FileSizeKb` DOUBLE NOT NULL DEFAULT '0',
	`FileSizeMb` DOUBLE NOT NULL DEFAULT '0',
	`FileSizeGb` DOUBLE NOT NULL DEFAULT '0',
	`Extension` VARCHAR(16) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`FileName` VARCHAR(256) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`FilePath` VARCHAR(1024) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`PathSegment01` VARCHAR(128) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`PathSegment02` VARCHAR(128) NOT NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
	`PathSegment03` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`PathSegment04` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`PathSegment05` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`PathSegment06` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`PathSegment07` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`PathSegment08` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`PathSegment09` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`PathSegment10` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`VideoResolution` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`IsVideoFile` BIT(1) NULL DEFAULT b'0',
	`HasSubtitles` BIT(1) NULL DEFAULT b'0',
	`FrameRate` DOUBLE NULL DEFAULT NULL,
	`VideoWidth` SMALLINT(6) NULL DEFAULT '0',
	`VideoHeight` SMALLINT(6) NULL DEFAULT '0',
	`AudioStreamCount` TINYINT(4) NULL DEFAULT '0',
	`VideoStreamCount` TINYINT(4) NULL DEFAULT '0',
	`SubtitleCount` TINYINT(4) NULL DEFAULT '0',
	`VideoDuration` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`VideoDurationSec` DOUBLE NULL DEFAULT NULL,
	PRIMARY KEY (`FileId`) USING BTREE,
	INDEX `Extension` (`Extension`) USING BTREE,
	INDEX `IsVideoFile` (`IsVideoFile`) USING BTREE,
	INDEX `HasSubtitles` (`HasSubtitles`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
